.\" Process this file with
.\" groff -man -Tascii chemtkrc.5
.\"
.TH chemtkrc 5 "JANUARY 2015" Linux "Configuration Files"
.SH NAME
~/.chemtkrc \- ncurses chemistry toolkit and scientific calculator
.SH DESCRIPTION
A
.BR ncurses (3)
chemistry toolkit and scientific calculator configuration file.
.SH ATTRIBUTES
Configuration is defined through
.B attributes
assigned with the syntax
.BI "attribute = [" "VALUE" "]"
.

.I color
.RS
Changes the color of the output. Valid colors are one of
.IR "read blue green yellow orange purple black" " or " "white" "."
.SH AUTHOR
Alex Striff <alex.striff1@gmail.com>
.SH "SEE ALSO"
.BR chemtk(1)
