language: c

sudo: false

addons:
  apt:
    packages:
      - autoconf
      - automake
      - libtool
      - libyaml-dev
      - libreadline-dev
      - doxygen
      - graphviz
      - texlive
      - pgf

cache:
  directories:
    - $HOME/build/jfjhh/chemtk/data
    - $HOME/build/jfjhh/chemtk/autom4te.cache
    - $HOME/build/jfjhh/chemtk/m4

script:
    - ./bootstrap
    - ./configure
    - make

