language: c

sudo: false

addons:
  apt:
    packages:
      - libyaml-dev
      - libreadline-dev

cache:
  directories:
    - $HOME/build/jfjhh/chemtk/data
    - $HOME/build/jfjhh/chemtk/autom4te.cache
    - $HOME/build/jfjhh/chemtk/m4

script:
  - mkdir -p m4
  - autoreconf -ivfs
  - ./configure --prefix=`pwd`/_dist
  - make
  - make install
  - make uninstall

